### ISSUE TITLE
Assertion `svfCall->getType()->isPointerTy() && "The operand should be a pointer type!"' failed

### ISSUE THREAD

**Issue by vwvw** [SVF-tools/SVF#1167]
Hi, similarly to #1071,  I am analyzing libxml2 compiled with -O0 -g, but SVF crashes during the analysis.

SVF commit: d43e92ed2b5590cfcb42c302e3ab3b89080f8d50 (2 weeks ago)
libxml2 7846b0a677f8d3ce72486125fa281e92ac9970e8 (https://github.com/GNOME/libxml2)

clang version 14.0.0 (installed by SVF)

Target: x86_64-unknown-linux-gnu
Thread model: posix

My code: 
```C++
#include "Graphs/SVFG.h"
#include "WPA/TypeAnalysis.h"
#include "SVF-LLVM/SVFIRBuilder.h"
#include "SVF-LLVM/LLVMUtil.h"

using namespace std;
using namespace SVF;
using namespace SVFUtil;
using namespace LLVMUtil;


int main(int argc, char ** argv)
{   
    int arg_num = 0;
    char **arg_value = new char*[argc];
    std::vector<std::string> moduleNameVec;
    LLVMUtil::processArguments(argc, argv, arg_num, arg_value, moduleNameVec);
    SVFModule* svfModule = LLVMModuleSet::getLLVMModuleSet()->buildSVFModule(moduleNameVec);

    SVFIRBuilder builder(svfModule);
    SVFIR* pag = builder.build();
    FlowSensitive* point_to_analysys = FlowSensitive::createFSWPA(pag);

    PTACallGraph* callgraph = point_to_analysys->getPTACallGraph();
    builder.updateCallGraph(callgraph);
    return 0;
}

```

which results in this error: `/home/libfuzz/SVF/svf-llvm/lib/SVFIRExtAPI.cpp:114: virtual SVF::NodeID SVF::SVFIRBuilder::getExtID(SVF::ExtAPI::OperationType, const string&, const SVF::SVFCallInst*): Assertion `svfCall->getType()->isPointerTy() && "The operand should be a pointer type!"' failed.`

Here is the stacktrace: 
```gdb
0x00007fc05178100b in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007fc05178100b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fc051760859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fc051760729 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007fc051771fd6 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000560505193caf in SVF::SVFIRBuilder::getExtID(SVF::ExtAPI::OperationType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, SVF::SVFCallInst const*) ()
#5  0x00005605051947dd in SVF::SVFIRBuilder::parseAtomaticOp(SVF::ExtAPI::Operand&, SVF::SVFCallInst const*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned int> > >&) ()
#6  0x000056050518c629 in SVF::SVFIRBuilder::parseExtFunctionOps(SVF::ExtAPI::ExtFunctionOps&, SVF::SVFCallInst const*) ()
#7  0x0000560505190b1c in SVF::SVFIRBuilder::handleExtCall(SVF::SVFInstruction const*, SVF::SVFFunction const*) ()
#8  0x0000560505183ea9 in SVF::SVFIRBuilder::updateCallGraph(SVF::PTACallGraph*) ()
#9  0x000056050515452e in main (argc=15, argv=0x7ffe59f13058)

```
Any idea what could cause this?
Attached is the bc file I tried to analyze [libxml2.a.bc.zip](https://github.com/SVF-tools/SVF/files/12360130/libxml2.a.bc.zip)

**Comment by yuleisui** [comment]
Are you using the latest SVF? @shuangxiangkan can you take a look? It seems caused by your recent pull request

**Comment by shuangxiangkan** [comment]
You can try using the latest version of SVF, as the code that was causing errors has been modified in the latest SVF.

**Comment by vwvw** [comment]
Oh, indeed it was solved in the mean time. Thanks a lot for the amazing tool and the quick help!
