### ISSUE TITLE
WPAPass::alias segfaults

### ISSUE THREAD

**Issue by Shreeasish** [SVF-tools/SVF#125]
I'm trying to use the WPAPass for inter-procedural analysis however it crashes at `PAG::hasValueNode()`. I've detailed my pass registration and usage below.

` 
//add to pass manager
 legacy::PassManager pm;
  pm.add(new WPAPass());
.
.
.
//and add pass requirements here.
...::getAnalysisUsage(llvm::AnalysisUsage &info) const {
  info.addPreserved<AAResultsWrapperPass>();
  info.addRequired<WPAPass>();
.
.
.
//Pass Usage as below
auto* wpa = &getAnalysis<WPAPass>();
.
.
.
//getting alias results
llvm::AliasResult experiment = wpa->alias(storeInst, loadInst);
`

Here's the stack trace from SVF:
`
==18162==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000030 (pc 0x000000ac8a0d bp 0x7ffc91a86cb0 sp 0x7ffc91a86c90 T0)
==18162==The signal is caused by a READ memory access.
==18162==Hint: address points to the zero page.
    #0 0xac8a0c in PAG::hasValueNode(llvm::Value const*) /home/shreeasish/llvm/SVF/include/MemoryModel/PAG.h:368:16
    #1 0xac58d8 in WPAPass::alias(llvm::Value const*, llvm::Value const*) /home/shreeasish/llvm/SVF/lib/WPA/WPAPass.cpp:158:14
`

Am I incorrectly using the pass?
What would be the easiest alternative for getting inter-procedural aliasing results?

Thanks

**Comment by FrancisYL** [comment]
@Shreeasish I recently encountered the same problem and it's solved by building SVF as a shared library and invoked it through `opt`. You can take a look at #156. Hope that could be helpful.

**Comment by yuleisui** [comment]
#156

**Comment by yuleisui** [comment]
Thanks @FrancisYL. A pointer analysis option e.g., `-ander` is supposed to be added after `opt`. #156

**Comment by Shreeasish** [comment]
I ended up instantiating an AndersenWaveDiff object and sending it pointer pairs for aliasing information. 
Follow-up Question: This wouldn't lead to the same results, no?

**Comment by yuleisui** [comment]
Different Andersens' analyses in SVF will produce the same results. It just differs in analysis performance. `AndersenWaveDiff` is a highly optimised version of `Andersen`
