### ISSUE TITLE
How to run SVF on a C++ project?

### ISSUE THREAD

**Issue by hpate063** [SVF-tools/SVF#1424]
Hi, 

I am trying to analyze the source code of [srsRAN](https://github.com/srsran/srsRAN_Project) using SVF. I have SVF setup on by Ubuntu system and it works for a single C/C++ example file. 

I am unsure on how to move forward and analyze an large codebase using SVF. Can someone help me? Or share any pointers which might be useful?

Best,
Harsh

**Comment by jumormt** [comment]
You can use [wllvm](https://github.com/travitch/whole-program-llvm) or [gllvm](https://github.com/SRI-CSL/gllvm) to extract the linked bitcode of the codebase.

**Comment by hpate063** [comment]
Thanks! I used wllvm and I am able to generate the LLVM IR files. 

When I try to analyze any of the .bc files, I run into this error:

```
hpatel@genela-Precision-7960-Tower:~/code/srsRAN_Project/build$ ../../SVF/Debug-build/bin/wpa -ander apps/gnb/CMakeFiles/gnb.dir/.gnb.cpp.o.bc
wpa: /home/hpatel/code/SVF/svf-llvm/lib/CHGBuilder.cpp:520: void SVF::CHGBuilder::analyzeVTables(const Module&): Assertion `opcode == Instruction::IntToPtr' failed.
Aborted (core dumped)
```

Here's a backtrace from gdb if it helps:
```
(gdb) r -ander apps/gnb/CMakeFiles/gnb.dir/.gnb.cpp.o.bc
Starting program: /home/hpatel/code/SVF/Debug-build/bin/wpa -ander apps/gnb/CMakeFiles/gnb.dir/.gnb.cpp.o.bc
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
wpa: /home/hpatel/code/SVF/svf-llvm/lib/CHGBuilder.cpp:520: void SVF::CHGBuilder::analyzeVTables(const Module&): Assertion `opcode == Instruction::IntToPtr' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff0e969fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff0e969fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff0e42476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff0e287f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff0e2871b in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff0e39e96 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00005555556375e3 in SVF::CHGBuilder::analyzeVTables (this=0x7fffffffe0d8, M=...)
    at /home/hpatel/code/SVF/svf-llvm/lib/CHGBuilder.cpp:520
#6  0x000055555563523f in SVF::CHGBuilder::buildCHG (this=0x7fffffffe0d8)
    at /home/hpatel/code/SVF/svf-llvm/lib/CHGBuilder.cpp:78
#7  0x00005555555ff1bd in SVF::SVFIRBuilder::build (this=0x7fffffffe240)
    at /home/hpatel/code/SVF/svf-llvm/lib/SVFIRBuilder.cpp:70
#8  0x0000555555576efb in main (argc=3, argv=0x7fffffffe3e8) at /home/hpatel/code/SVF/svf-llvm/tools/WPA/wpa.cpp:65
(gdb)

```

Can you help me understand why this happens and how I can resolve it?

**Comment by yuleisui** [comment]
Could you upload your bc file?

**Comment by hpate063** [comment]
Here it is. 
[compressed .bc file.zip](https://github.com/SVF-tools/SVF/files/14877512/compressed.bc.file.zip)

**Comment by jumormt** [comment]
@hpate063 Did you use llvm 16 as the compiler?

**Comment by hpate063** [comment]
No. My system has clang version 14.0.0 right now. 
Should I try and update it to 16 or higher?

**Comment by jumormt** [comment]
@hpate063 it works fine on my end. Can you try the latest SVF?

**Comment by hpate063** [comment]
Yes, I did and it worked. Thank you @jumormt and @yuleisui for the help.
