### ISSUE TITLE
Potential bugs with several Pointer Analysis?

### ISSUE THREAD

**Issue by FrancisYL** [SVF-tools/SVF#163]
Hi,

I'm trying to use SVF to detect loop inter-iteration alias and have the following simple program
```
int main(int argc, char* argv[]) {
    int iterations = atoi(argv[1]);

    array[0] = 42;
    for (int i = 1; i < iterations; i++) {
      array[i] = array[i-1] * i;
    }

    print("%d\n", array[iterations-1];
    return 0;
}
```
the instruction `array[i] = array[i-1] * i` contains loop-carried memory dependency so I hope that the load from `array[i-1]` and the store to `array[i]` are alias to each other.

However, three pointer analysis
- -lander (Lazy cycle detection inclusion-based analysis), 
- -hlander (Hybrid lazy cycle detection inclusion-based analysis) and
- -type (Type-based fast analysis for Callgraph, PAG and CHA)
give me **NoAlias** results, which are not what I'm expecting. Why does that occur?

**Comment by yuleisui** [comment]
(1) Please tell us a bit more about your results. Which two pointers you picked for aliases analysis? Did you try to add a stub function similar as https://github.com/SVF-tools/PTABen/blob/master/basic_c_tests/array-varIdx.c ?

(2) Have you tried `-ander`?

**Comment by FrancisYL** [comment]
I wrote a pass to collect all memory instructions (load & store) and query them in pairs. The above sample code after translated into bitcode with -01 optimization is
```
; ModuleID = 'program.bc'
source_filename = "program.cpp"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@.str = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1

; Function Attrs: nofree norecurse nounwind uwtable
define dso_local i32 @main(i32, i8** nocapture readonly) local_unnamed_addr #0 {
  %3 = getelementptr inbounds i8*, i8** %1, i64 1
  %4 = load i8*, i8** %3, align 8, !tbaa !2
  %5 = tail call i32 @atoi(i8* %4) #3
  %6 = sext i32 %5 to i64
  %7 = shl nsw i64 %6, 2
  %8 = tail call noalias i8* @malloc(i64 %7) #4
  %9 = bitcast i8* %8 to i32*
  store i32 42, i32* %9, align 4, !tbaa !6
  %10 = icmp sgt i32 %5, 1
  br i1 %10, label %11, label %14

11:                                               ; preds = %2
  %12 = zext i32 %5 to i64
  %13 = load i32, i32* %9, align 4
  br label %20

14:                                               ; preds = %20, %2
  %15 = add nsw i32 %5, -1
  %16 = sext i32 %15 to i64
  %17 = getelementptr inbounds i32, i32* %9, i64 %16
  %18 = load i32, i32* %17, align 4, !tbaa !6
  %19 = tail call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), i32 %18)
  ret i32 0

20:                                               ; preds = %20, %11
  %21 = phi i32 [ %13, %11 ], [ %24, %20 ]
  %22 = phi i64 [ 1, %11 ], [ %26, %20 ]
  %23 = trunc i64 %22 to i32
  %24 = mul nsw i32 %21, %23
  %25 = getelementptr inbounds i32, i32* %9, i64 %22
  store i32 %24, i32* %25, align 4, !tbaa !6
  %26 = add nuw nsw i64 %22, 1
  %27 = icmp eq i64 %26, %12
  br i1 %27, label %14, label %20
}

; Function Attrs: inlinehint nounwind readonly uwtable
define available_externally dso_local i32 @atoi(i8* nonnull) local_unnamed_addr #1 {
  %2 = tail call i64 @strtol(i8* nocapture nonnull %0, i8** null, i32 10) #4
  %3 = trunc i64 %2 to i32
  ret i32 %3
}

; Function Attrs: nofree nounwind
declare dso_local noalias i8* @malloc(i64) local_unnamed_addr #2

; Function Attrs: nofree nounwind
declare dso_local i32 @printf(i8* nocapture readonly, ...) local_unnamed_addr #2

; Function Attrs: nofree nounwind
declare dso_local i64 @strtol(i8* readonly, i8** nocapture, i32) local_unnamed_addr #2

attributes #0 = { nofree norecurse nounwind uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { inlinehint nounwind readonly uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #2 = { nofree nounwind "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #3 = { nounwind readonly }
attributes #4 = { nounwind }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 9.0.0 (git@github.com:scampanoni/LLVM_installer.git 05e8bdd81a8fb30a2498881405757dbddd5535d6)"}
!2 = !{!3, !3, i64 0}
!3 = !{!"any pointer", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C++ TBAA"}
!6 = !{!7, !7, i64 0}
!7 = !{!"int", !4, i64 0}
```
When I query alias analysis between instructions
`store i32 42, i32* %9, align 4, !tbaa !6`,
`%13 = load i32, i32* %9, align 4`
`%18 = load i32, i32* %17, align 4, !tbaa !6` and
`store i32 %24, i32* %25, align 4, !tbaa !6`
The `-ander` pta gives me **MayAlias** between all of them while `-lander -hlander -type` all gave me result as **NoAlias**.

**Comment by yuleisui** [comment]
May I know which two pointers you are querying?

**Comment by yuleisui** [comment]
@kisslune please look at `-lander` and `-hlander`
@FrancisYL `-type` only supports call graph construction and CHA analysis but not alias analysis

**Comment by FrancisYL** [comment]
I didn't query alias between two pointers but two memory locations using the api `AliasResult alias(const MemoryLocation  &LocA, const MemoryLocation  &LocB)` provided in https://github.com/SVF-tools/SVF/blob/master/include/WPA/WPAPass.h#L84.

So for the example above, the memory location would be %9 in both `store i32 42, i32* %9, align 4, !tbaa !6` and `%13 = load i32, i32* %9, align 4`, %17 in `%18 = load i32, i32* %17, align 4, !tbaa !6` and %25 in `store i32 %24, i32* %25, align 4, !tbaa !6`.

Please correct me if I'm using SVF alias analysis in the wrong way. Thanks!

**Comment by kisslune** [comment]
Hello FrancisYL,

The bugs of -lander and -hlander are fixed in the newest patch.

Please wait for around 2 hours to download the newest version.

**Comment by yuleisui** [comment]
@kisslune thanks, I will merge it now. @FrancisYL you are good to go and thanks for reporting this.

**Comment by FrancisYL** [comment]
@yuleisui @kisslune Thank you for fixing the bug. Now both `-lander -hlander` give **MayAlias** result.

**Comment by FrancisYL** [comment]
I also encountered a segmentation fault using `-andertype (Diff wave propagation with type inclusion-based analysis)` and don't know why is that happened? Here are the backtrace from gdb
```
#0  0x00007ffff636ba12 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, TypeSet*>, std::_Select1st<std::pair<unsigned int const, TypeSet*> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, TypeSet*> > >::_M_begin (this=0x0)
    at /files/opt-rh/devtoolset-8/root/usr/include/c++/8/bits/stl_tree.h:753
#1  0x00007ffff63edfe2 in std::_Rb_tree<unsigned int, std::pair<unsigned int const, TypeSet*>, std::_Select1st<std::pair<unsigned int const, TypeSet*> >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, TypeSet*> > >::find (this=0x0, __k=@0x7fffffffd1a4: 20)
    at /files/opt-rh/devtoolset-8/root/usr/include/c++/8/bits/stl_tree.h:2539
#2  0x00007ffff63ecfdd in std::map<unsigned int, TypeSet*, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, TypeSet*> > >::find (this=0x0, __x=@0x7fffffffd1a4: 20) at /files/opt-rh/devtoolset-8/root/usr/include/c++/8/bits/stl_map.h:1169
#3  0x00007ffff63ec6c3 in TypeSystem::addTypeForVar (this=0x0, var=20, type=...) at /home/yso0488/projects/SVF-9/include/MemoryModel/PTAType.h:209
#4  0x00007ffff63ec7a7 in TypeSystem::addTypeForVar (this=0x0, var=20, type=0x26a7600) at /home/yso0488/projects/SVF-9/include/MemoryModel/PTAType.h:225
#5  0x00007ffff63eb55e in AndersenWaveDiffWithType::updateObjType (this=0x2681a60, type=0x26a7600, objs=...) at /home/yso0488/projects/SVF-9/lib/WPA/AndersenWaveDiffWithType.cpp:30
#6  0x00007ffff63eb44d in AndersenWaveDiffWithType::processCast (this=0x2681a60, edge=0x272ad20) at /home/yso0488/projects/SVF-9/lib/WPA/AndersenWaveDiffWithType.cpp:17
#7  0x00007ffff63e9ff2 in AndersenWaveDiff::processCopy (this=0x2681a60, node=19, edge=0x272ad20) at /home/yso0488/projects/SVF-9/lib/WPA/AndersenWaveDiff.cpp:179
#8  0x00007ffff63e9cbd in AndersenWaveDiff::handleCopyGep (this=0x2681a60, node=0x2723550) at /home/yso0488/projects/SVF-9/lib/WPA/AndersenWaveDiff.cpp:132
#9  0x00007ffff63e99f7 in AndersenWaveDiff::processNode (this=0x2681a60, nodeId=19) at /home/yso0488/projects/SVF-9/lib/WPA/AndersenWaveDiff.cpp:91
#10 0x00007ffff63e980d in AndersenWaveDiff::solveWorklist (this=0x2681a60) at /home/yso0488/projects/SVF-9/lib/WPA/AndersenWaveDiff.cpp:50
#11 0x00007ffff63c5cfe in WPASolver<ConstraintGraph*>::solve (this=0x2681a60) at /home/yso0488/projects/SVF-9/include/WPA/WPASolver.h:102
#12 0x00007ffff63d88fe in Andersen::analyze (this=0x2681a60, svfModule=...) at /home/yso0488/projects/SVF-9/lib/WPA/Andersen.cpp:80
#13 0x00007ffff63fb001 in WPAPass::runPointerAnalysis (this=0x268db10, svfModule=..., kind=7) at /home/yso0488/projects/SVF-9/lib/WPA/WPAPass.cpp:149
#14 0x00007ffff63facc1 in WPAPass::runOnModule (this=0x268db10, svfModule=...) at /home/yso0488/projects/SVF-9/lib/WPA/WPAPass.cpp:100
#15 0x00007ffff63fc491 in WPAPass::runOnModule (this=0x268db10, module=...) at /home/yso0488/projects/SVF-9/include/WPA/WPAPass.h:97
#16 0x0000000000fe14fa in llvm::legacy::PassManagerImpl::run(llvm::Module&) ()
#17 0x00000000006c3503 in main ()
```

The command I ran are
`wpa -andertype program.bc`
and
`opt -load ~/projects/SVF-9/Debug-build/lib/libSvf.so -load ~/projects/SVF-9/Debug-build/lib/CUDD/libCudd.so -load ~/CAT/lib/CAT.so program.bc -CAT -andertype -disable-output`

**Comment by yuleisui** [comment]
@FrancisYL Thanks for trying this new option. The underlying type-based analysis is still under development. We will update you once it is done in a couple of months. I have added an assertion to make this clear (see dfa88aab87ce889173fce443770145ce444609fc).

**Comment by FrancisYL** [comment]
@yuleisui Thank you and looking forward to that.
