### ISSUE TITLE
Segmentation fault occurs in CHGraph::buildCHG() for constructor who has indirect call

### ISSUE THREAD

**Issue by FrancisYL** [SVF-tools/SVF#204]
Hi, an segmentation occurs during the construction of `CHGraph` for the constructor method who has indirect calls in it. I found the bug in
https://github.com/SVF-tools/SVF/blob/e3d5175d50ee9219a607685b39d0b86014329dd8/lib/SVF-FE/CHA.cpp#L171
since `getcallee(cs)` returns NULL for indirect callsite, it then fails the following assertion in
https://github.com/SVF-tools/SVF/blob/e3d5175d50ee9219a607685b39d0b86014329dd8/include/Util/BasicTypes.h#L216

Here's a demonstrating example and its backtrace
```C++
class A {
  public:
    A (bool b, int v) {
      void (A::*f)(int) = nullptr;
      
      if (b)
        f = &A::set1;
      else
        f = &A::set2;

      (*this.*f)(v);  // indirect call
    }

    void set1(int v) {
      this->value = v;
    }

    void set2(int v) {
      this->value = v;
    }

  private:
    int value;
};

int main() {
  A *a = new A(false, 10);
  
  return 0;
}
```
```
#0  0x00007ffff7839370 in SVFFunction::getLLVMFun (this=0x0) at /home/yso0488/projects/SVF/include/Util/BasicTypes.h:216
#1  0x00007ffff78a8aba in CHGraph::connectInheritEdgeViaCall (this=0xd62000, callerfun=0xceeac0, cs=...) at /home/yso0488/projects/SVF/lib/SVF-FE/CHA.cpp:172
#2  0x00007ffff78a89f1 in CHGraph::buildCHGEdges (this=0xd62000, fun=0xceeac0) at /home/yso0488/projects/SVF/lib/SVF-FE/CHA.cpp:155
#3  0x00007ffff78a824d in CHGraph::buildCHG (this=0xd62000) at /home/yso0488/projects/SVF/lib/SVF-FE/CHA.cpp:97
#4  0x00007ffff7979e7c in PointerAnalysis::initialize (this=0xcf85e8, svfModule=0xce7020) at /home/yso0488/projects/SVF/lib/MemoryModel/PointerAnalysis.cpp:151
#5  0x00007ffff79b338d in Andersen::initialize (this=0xcf8540, svfModule=0xce7020) at /home/yso0488/projects/SVF/lib/WPA/Andersen.cpp:99
#6  0x00007ffff79b3107 in Andersen::analyze (this=0xcf8540, svfModule=0xce7020) at /home/yso0488/projects/SVF/lib/WPA/Andersen.cpp:71
#7  0x00007ffff79d96df in WPAPass::runPointerAnalysis (this=0xcf52c0, svfModule=0xce7020, kind=6) at /home/yso0488/projects/SVF/lib/WPA/WPAPass.cpp:149
#8  0x00007ffff79d934a in WPAPass::runOnModule (this=0xcf52c0, svfModule=0xce7020) at /home/yso0488/projects/SVF/lib/WPA/WPAPass.cpp:100
#9  0x000000000041c88a in main (argc=3, argv=0x7fffffffdd88) at /home/yso0488/projects/SVF/tools/WPA/wpa.cpp:51
```

**Comment by swthorn** [comment]
Can confirm, also getting this seg fault.

**Comment by yuleisui** [comment]
Have this patch solved the problem?
https://github.com/SVF-tools/SVF/pull/205

**Comment by yuleisui** [comment]
Thanks for reporting. Just fixed in this patch https://github.com/SVF-tools/SVF/commit/e6c4fedb5008b9d11125d62e63bb379a53b69514
