### ISSUE TITLE
Assertion error: wpa: ../include/Graphs/VFG.h:409: SVF::NodeID SVF::VFG::getDef(const SVF::PAGNode*) const: Assertion `it!=PAGNodeToDefMap.end() && "PAG node does not have a definition??"' failed

### ISSUE THREAD

**Issue by gerion0** [SVF-tools/SVF#318]
When executing SVF with a larger test case, I got this error:
```
wpa: ../include/Graphs/VFG.h:409: SVF::NodeID SVF::VFG::getDef(const SVF::PAGNode*) const: Assertion `it!=PAGNodeToDefMap.end() && "PAG node does not have a definition??"' failed
```

I have modified SVF with this patch to get better printf debugging:
```diff
diff --git a/lib/Graphs/VFG.cpp b/lib/Graphs/VFG.cpp
index 2012ab5..17545bf 100644
--- a/lib/Graphs/VFG.cpp
+++ b/lib/Graphs/VFG.cpp
@@ -572,20 +572,29 @@ VFGEdge* VFG::addRetEdge(NodeID srcId, NodeID dstId, CallSiteID csId)
  */
 void VFG::connectDirectVFGEdges()
 {
+    llvm::errs() << "CONNECTDIRECTVFGEDGES\n";
 
     for(iterator it = begin(), eit = end(); it!=eit; ++it)
     {
         NodeID nodeId = it->first;
         VFGNode* node = it->second;
 
+        llvm::errs() << "NODEID: " << nodeId << "\n";
+        llvm::errs() << "NODE: " << *node << "\n";
+
+
         if(StmtVFGNode* stmtNode = SVFUtil::dyn_cast<StmtVFGNode>(node))
         {
+            llvm::errs() << "STMTVFGNODE\n";
             /// do not handle AddrSVFG node, as it is already the source of a definition
             if(SVFUtil::isa<AddrVFGNode>(stmtNode))
                 continue;
             /// for all other cases, like copy/gep/load/ret, connect the RHS pointer to its def
             if (stmtNode->getPAGSrcNode()->isConstantData() == false)
+                llvm::errs() << "fail\n";
+                llvm::errs() << "SRCNode: " << *stmtNode->getPAGSrcNode() << "\n";
                 addIntraDirectVFEdge(getDef(stmtNode->getPAGSrcNode()), nodeId);
+                llvm::errs() << "fail_after\n";
 
             /// for store, connect the RHS/LHS pointer to its def
             if(SVFUtil::isa<StoreVFGNode>(stmtNode) && (stmtNode->getPAGDstNode()->isConstantData() == false))
@@ -596,10 +605,14 @@ void VFG::connectDirectVFGEdges()
         }
         else if(PHIVFGNode* phiNode = SVFUtil::dyn_cast<PHIVFGNode>(node))
         {
+            llvm::errs() << "PHIVFGNODE\n";
             for (PHIVFGNode::OPVers::const_iterator it = phiNode->opVerBegin(), eit = phiNode->opVerEnd(); it != eit; it++)
             {
+                llvm::errs() << "itsecond: " << *it->second << "\n";
                 if (it->second->isConstantData() == false)
+                    llvm::errs() << "addintraedge\n";
                     addIntraDirectVFEdge(getDef(it->second), nodeId);
+                    llvm::errs() << "addintraedge_after\n";
             }
         }
         else if(BinaryOPVFGNode* binaryNode = SVFUtil::dyn_cast<BinaryOPVFGNode>(node))
@@ -672,6 +685,7 @@ void VFG::connectDirectVFGEdges()
         FormalRetVFGNode* calleeRet = getFormalRetVFGNode(joinedge->getSrcNode());
         addRetEdge(calleeRet->getId(),callsiteRev, getCallSiteID(joinedge->getCallSite(), calleeRet->getFun()));
     }
+       llvm::errs() << "CONNECTDIRECTVFGEDGES_END\n";
 }
 
 /*!
```
My execution command is:
```
./bin/wpa --ander --svfg --dump-svfg test.ll
```

The (relevant) log is:
```
...
NODEID: 40226
NODE: StoreVFGNode ID: 40226 StorePE: [33409<--33476]	 store double %fneg, double* %number.addr, align 8, !dbg !8026{ ln: 264 fl: ../appl/FreeRTOS/GPSLogger/Libs/arduino/Print.cpp }
STMTVFGNODE
fail
SRCNode: ValPN ID: 33476   %fneg = fneg fast double %10, !dbg !8025 { ln: 264 fl: ../appl/FreeRTOS/GPSLogger/Libs/arduino/Print.cpp }
wpa: ../include/Graphs/VFG.h:409: SVF::NodeID SVF::VFG::getDef(const SVF::PAGNode*) const: Assertion `it!=PAGNodeToDefMap.end() && "PAG node does not have a definition??"' failed.
```

This is the stack trace (I'm not sure, why gdb does not find the source files):
```
(gdb) bt
#0  0x00007ffff28e935d in raise () at /lib64/libc.so.6
#1  0x00007ffff28d256b in abort () at /lib64/libc.so.6
#2  0x00007ffff28d2433 in _nl_load_domain.cold () at /lib64/libc.so.6
#3  0x00007ffff28e17f1 in  () at /lib64/libc.so.6
#4  0x00007ffff7d1c32a in SVF::VFG::getDef(SVF::PAGNode const*) const () at /home/ci3nt/sourcecode/ara/subprojects/svf/build/lib/libSvf.so.10
#5  0x00007ffff7db7828 in SVF::VFG::connectDirectVFGEdges() () at /home/ci3nt/sourcecode/ara/subprojects/svf/build/lib/libSvf.so.10
#6  0x00007ffff7dbb87d in SVF::VFG::VFG(SVF::PTACallGraph*, SVF::VFG::VFGK) () at /home/ci3nt/sourcecode/ara/subprojects/svf/build/lib/libSvf.so.10
#7  0x00007ffff7d85eb7 in SVF::SVFG::SVFG(SVF::MemSSA*, SVF::VFG::VFGK) () at /home/ci3nt/sourcecode/ara/subprojects/svf/build/lib/libSvf.so.10
#8  0x00007ffff7deac18 in SVF::SVFGBuilder::build(SVF::BVDataPTAImpl*, SVF::VFG::VFGK) () at /home/ci3nt/sourcecode/ara/subprojects/svf/build/lib/libSvf.so.10
#9  0x00007ffff7ecbdb8 in SVF::WPAPass::runPointerAnalysis(SVF::SVFModule*, unsigned int) ()
    at /home/ci3nt/sourcecode/ara/subprojects/svf/build/lib/libSvf.so.10
#10 0x00007ffff7ecbf6b in SVF::WPAPass::runOnModule(SVF::SVFModule*) () at /home/ci3nt/sourcecode/ara/subprojects/svf/build/lib/libSvf.so.10
#11 0x0000555555556366 in main ()
```

This is the Print.cpp file where the error occurs: https://github.com/grafalex82/GPSLogger/blob/master/Libs/MiniArduino/Print.cpp#L264

This should be the corresponding IR:
```llvm
; Function Attrs: noinline nounwind optnone
define dso_local i32 @_ZN5Print10printFloatEdh(%class.Print* %this, double %number, i8 zeroext %digits) #0 align 2 !dbg !27390 {
entry:
  %retval = alloca i32, align 4
  %this.addr = alloca %class.Print*, align 4
  %number.addr = alloca double, align 8
  %digits.addr = alloca i8, align 1
  %n = alloca i32, align 4
  %rounding = alloca double, align 8
  %i = alloca i8, align 1
  %int_part = alloca i32, align 4
  %remainder = alloca double, align 8
  %toPrint = alloca i32, align 4
  store %class.Print* %this, %class.Print** %this.addr, align 4
  call void @llvm.dbg.declare(metadata %class.Print** %this.addr, metadata !27391, metadata !DIExpression()), !dbg !27392
  store double %number, double* %number.addr, align 8
  call void @llvm.dbg.declare(metadata double* %number.addr, metadata !27393, metadata !DIExpression()), !dbg !27394
  store i8 %digits, i8* %digits.addr, align 1
  call void @llvm.dbg.declare(metadata i8* %digits.addr, metadata !27395, metadata !DIExpression()), !dbg !27396
  %this1 = load %class.Print*, %class.Print** %this.addr, align 4
  call void @llvm.dbg.declare(metadata i32* %n, metadata !27397, metadata !DIExpression()), !dbg !27398
  store i32 0, i32* %n, align 4, !dbg !27398
  %0 = load double, double* %number.addr, align 8, !dbg !27399
  %call = call i32 @__fpclassifyd(double %0) #10, !dbg !27399
  %cmp = icmp eq i32 %call, 0, !dbg !27399
  br i1 %cmp, label %if.then, label %if.end, !dbg !27401

if.then:                                          ; preds = %entry
  %call2 = call i32 @_ZN5Print5printEPKc(%class.Print* %this1, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.1.277, i32 0, i32 0)) #10, !dbg !27402
  store i32 %call2, i32* %retval, align 4, !dbg !27403
  br label %return, !dbg !27403

if.end:                                           ; preds = %entry
  %1 = load double, double* %number.addr, align 8, !dbg !27404
  %call3 = call i32 @__fpclassifyd(double %1) #10, !dbg !27404
  %cmp4 = icmp eq i32 %call3, 1, !dbg !27404
  br i1 %cmp4, label %if.then5, label %if.end7, !dbg !27406

if.then5:                                         ; preds = %if.end
  %call6 = call i32 @_ZN5Print5printEPKc(%class.Print* %this1, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.2.278, i32 0, i32 0)) #10, !dbg !27407
  store i32 %call6, i32* %retval, align 4, !dbg !27408
  br label %return, !dbg !27408

if.end7:                                          ; preds = %if.end
  %2 = load double, double* %number.addr, align 8, !dbg !27409
  %cmp8 = fcmp fast ogt double %2, 0x41EFFFFFE0000000, !dbg !27411
  br i1 %cmp8, label %if.then9, label %if.end11, !dbg !27412

if.then9:                                         ; preds = %if.end7
  %call10 = call i32 @_ZN5Print5printEPKc(%class.Print* %this1, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.3.279, i32 0, i32 0)) #10, !dbg !27413
  store i32 %call10, i32* %retval, align 4, !dbg !27414
  br label %return, !dbg !27414

if.end11:                                         ; preds = %if.end7
  %3 = load double, double* %number.addr, align 8, !dbg !27415
  %cmp12 = fcmp fast olt double %3, 0xC1EFFFFFE0000000, !dbg !27417
  br i1 %cmp12, label %if.then13, label %if.end15, !dbg !27418

if.then13:                                        ; preds = %if.end11
  %call14 = call i32 @_ZN5Print5printEPKc(%class.Print* %this1, i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.3.279, i32 0, i32 0)) #10, !dbg !27419
  store i32 %call14, i32* %retval, align 4, !dbg !27420
  br label %return, !dbg !27420

if.end15:                                         ; preds = %if.end11
  %4 = load double, double* %number.addr, align 8, !dbg !27421
  %cmp16 = fcmp fast olt double %4, 0.000000e+00, !dbg !27423
  br i1 %cmp16, label %if.then17, label %if.end19, !dbg !27424

if.then17:                                        ; preds = %if.end15
  %call18 = call i32 @_ZN5Print5printEc(%class.Print* %this1, i8 zeroext 45) #10, !dbg !27425
  %5 = load i32, i32* %n, align 4, !dbg !27427
  %add = add i32 %5, %call18, !dbg !27427
  store i32 %add, i32* %n, align 4, !dbg !27427
  %6 = load double, double* %number.addr, align 8, !dbg !27428
  %fneg = fneg fast double %6, !dbg !27429
  store double %fneg, double* %number.addr, align 8, !dbg !27430
  br label %if.end19, !dbg !27431

if.end19:                                         ; preds = %if.then17, %if.end15
  call void @llvm.dbg.declare(metadata double* %rounding, metadata !27432, metadata !DIExpression()), !dbg !27433
  store double 5.000000e-01, double* %rounding, align 8, !dbg !27433
  call void @llvm.dbg.declare(metadata i8* %i, metadata !27434, metadata !DIExpression()), !dbg !27436
  store i8 0, i8* %i, align 1, !dbg !27436
  br label %for.cond, !dbg !27437

for.cond:                                         ; preds = %for.inc, %if.end19
  %7 = load i8, i8* %i, align 1, !dbg !27438
  %conv = zext i8 %7 to i32, !dbg !27438
  %8 = load i8, i8* %digits.addr, align 1, !dbg !27440
  %conv20 = zext i8 %8 to i32, !dbg !27440
  %cmp21 = icmp slt i32 %conv, %conv20, !dbg !27441
  br i1 %cmp21, label %for.body, label %for.end, !dbg !27442

for.body:                                         ; preds = %for.cond
  %9 = load double, double* %rounding, align 8, !dbg !27443
  %div = fdiv fast double %9, 1.000000e+01, !dbg !27443
  store double %div, double* %rounding, align 8, !dbg !27443
  br label %for.inc, !dbg !27444

for.inc:                                          ; preds = %for.body
  %10 = load i8, i8* %i, align 1, !dbg !27445
  %inc = add i8 %10, 1, !dbg !27445
  store i8 %inc, i8* %i, align 1, !dbg !27445
  br label %for.cond, !dbg !27446, !llvm.loop !27447

for.end:                                          ; preds = %for.cond
  %11 = load double, double* %rounding, align 8, !dbg !27449
  %12 = load double, double* %number.addr, align 8, !dbg !27450
  %add22 = fadd fast double %12, %11, !dbg !27450
  store double %add22, double* %number.addr, align 8, !dbg !27450
  call void @llvm.dbg.declare(metadata i32* %int_part, metadata !27451, metadata !DIExpression()), !dbg !27452
  %13 = load double, double* %number.addr, align 8, !dbg !27453
  %conv23 = fptoui double %13 to i32, !dbg !27453
  store i32 %conv23, i32* %int_part, align 4, !dbg !27452
  call void @llvm.dbg.declare(metadata double* %remainder, metadata !27454, metadata !DIExpression()), !dbg !27455
  %14 = load double, double* %number.addr, align 8, !dbg !27456
  %15 = load i32, i32* %int_part, align 4, !dbg !27457
  %conv24 = uitofp i32 %15 to double, !dbg !27457
  %sub = fsub fast double %14, %conv24, !dbg !27458
  store double %sub, double* %remainder, align 8, !dbg !27455
  %16 = load i32, i32* %int_part, align 4, !dbg !27459
  %call25 = call i32 @_ZN5Print5printEmi(%class.Print* %this1, i32 %16, i32 10) #10, !dbg !27460
  %17 = load i32, i32* %n, align 4, !dbg !27461
  %add26 = add i32 %17, %call25, !dbg !27461
  store i32 %add26, i32* %n, align 4, !dbg !27461
  %18 = load i8, i8* %digits.addr, align 1, !dbg !27462
  %conv27 = zext i8 %18 to i32, !dbg !27462
  %cmp28 = icmp sgt i32 %conv27, 0, !dbg !27464
  br i1 %cmp28, label %if.then29, label %if.end32, !dbg !27465

if.then29:                                        ; preds = %for.end
  %call30 = call i32 @_ZN5Print5printEc(%class.Print* %this1, i8 zeroext 46) #10, !dbg !27466
  %19 = load i32, i32* %n, align 4, !dbg !27468
  %add31 = add i32 %19, %call30, !dbg !27468
  store i32 %add31, i32* %n, align 4, !dbg !27468
  br label %if.end32, !dbg !27469

if.end32:                                         ; preds = %if.then29, %for.end
  br label %while.cond, !dbg !27470

while.cond:                                       ; preds = %while.body, %if.end32
  %20 = load i8, i8* %digits.addr, align 1, !dbg !27471
  %dec = add i8 %20, -1, !dbg !27471
  store i8 %dec, i8* %digits.addr, align 1, !dbg !27471
  %conv33 = zext i8 %20 to i32, !dbg !27472
  %cmp34 = icmp sgt i32 %conv33, 0, !dbg !27473
  br i1 %cmp34, label %while.body, label %while.end, !dbg !27470

while.body:                                       ; preds = %while.cond
  %21 = load double, double* %remainder, align 8, !dbg !27474
  %mul = fmul fast double %21, 1.000000e+01, !dbg !27474
  store double %mul, double* %remainder, align 8, !dbg !27474
  call void @llvm.dbg.declare(metadata i32* %toPrint, metadata !27476, metadata !DIExpression()), !dbg !27477
  %22 = load double, double* %remainder, align 8, !dbg !27478
  %conv35 = fptoui double %22 to i32, !dbg !27479
  store i32 %conv35, i32* %toPrint, align 4, !dbg !27477
  %23 = load i32, i32* %toPrint, align 4, !dbg !27480
  %call36 = call i32 @_ZN5Print5printEji(%class.Print* %this1, i32 %23, i32 10) #10, !dbg !27481
  %24 = load i32, i32* %n, align 4, !dbg !27482
  %add37 = add i32 %24, %call36, !dbg !27482
  store i32 %add37, i32* %n, align 4, !dbg !27482
  %25 = load i32, i32* %toPrint, align 4, !dbg !27483
  %conv38 = uitofp i32 %25 to double, !dbg !27483
  %26 = load double, double* %remainder, align 8, !dbg !27484
  %sub39 = fsub fast double %26, %conv38, !dbg !27484
  store double %sub39, double* %remainder, align 8, !dbg !27484
  br label %while.cond, !dbg !27470, !llvm.loop !27485

while.end:                                        ; preds = %while.cond
  %27 = load i32, i32* %n, align 4, !dbg !27487
  store i32 %27, i32* %retval, align 4, !dbg !27488
  br label %return, !dbg !27488

return:                                           ; preds = %while.end, %if.then13, %if.then9, %if.then5, %if.then
  %28 = load i32, i32* %retval, align 4, !dbg !27489
  ret i32 %28, !dbg !27489
}
```

**Comment by gerion0** [comment]
Whoops, nevermind, should have pulled. Is already fixed in the current master...
